coverage:
  precision: 2
  round: down
  range: "30...80"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto 

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: no        
  require_head: yes      
  branches:              
    - "master"
